version: '3.8'
services:
  app:
    image: nando2302/tangkasnginx:1.0
    ports:
      - target: 80
        published: 80
        protocol: tcp
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      placement:
        constraints: [node.role == worker]
    

  haproxy_lb:
    image: nando2302/lb-haproxy:2.0
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    deploy:
      update_config:
        parallelism: 0
        delay: 10s
        failure_action:  rollback
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure